CREATE TABLE Payments (
    id INT PRIMARY KEY IDENTITY(1000,1),
    user_id INTEGER NOT NULL,
    order_id INTEGER NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    payment_status VARCHAR(255) NOT NULL,
    created_at DATE NOT NULL DEFAULT GETDATE(),
    CHECK (user_id > 0),
    CHECK (order_id > 0),
    CHECK (amount > 0),
    CHECK (payment_method <> ''),
    CHECK (payment_status <> ''),
    CHECK (created_at <= GETDATE()),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
);