CREATE TABLE Reviews (
    id INT PRIMARY KEY IDENTITY(1000,1),
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    rating INTEGER NOT NULL,
    review VARCHAR(255) NOT NULL,
    created_at DATE NOT NULL DEFAULT GETDATE(),
    CHECK (user_id > 0),
    CHECK (product_id > 0),
    CHECK (rating > 0),
    CHECK (review <> ''),
    CHECK (created_at <= GETDATE()),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES products(id),
);